apiVersion: apps/v1
kind: Deployment
metadata:
  name: hugo-deploy
  labels:
    app: hugo
  namespace: blog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
        - name: blog
          image: registry.cn-hangzhou.aliyuncs.com/incubator4/hugo-blog:{{.image_tag}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "25m"
            limits:
              memory: "128Mi"
              cpu: "50m"
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: blog-svc
  namespace: blog
spec:
  selector:
    app: hugo
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: blog-redirectscheme
  namespace: blog
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: blog-ingress
  namespace: blog
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`blog.incubator4.com`)
      kind: Rule
      middlewares:                    # [5]
        - name: blog-redirectscheme             # [6]
      services:
        - name: blog-svc
          port: 80


