apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: blog-incubator4-tls
  namespace: blog
spec:
  secretName: blog-incubator4-tls
  dnsNames:
    - blog.incubator4.com
    - blog.k3s.incubator4.com
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer