name: Deploy

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: danielr1996/kubectl-action@1.0.0
        name: Deploy to Kubernetes
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: apply -f deploy.yaml
      - uses: danielr1996/kubectl-action@1.0.0
        name: Update Image
        with:
          kubeconfig: ${{ secrets.KUBE_CONFIG }}
          args: set image deployment/hugo-deploy  blog=registry.cn-hangzhou.aliyuncs.com/incubator4/hugo-blog:${{ env.RELEASE_VERSION }} -n blog
